import type { Metadata } from "next";
import "./globals.css";
import Providers from '@/contexts/NextUiProv'
import Nav from '@/components/navBar/navbar'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: "Mega Tel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
      <Providers>
          <Nav/>
          {children}
          <Footer/>
      </Providers>
      </body>
    </html>
  );
}
